language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - TOXENV=py26-1.5
  - TOXENV=py27-1.5
  - TOXENV=py33-1.5
  - TOXENV=docs
  - TOXENV=py26-dev,py27-dev,py33-dev

matrix:
  allow_failures:
    - env: TOXENV=py26-dev,py27-dev

# command to install dependencies
install:
    - pip install tox

# command to run tests
script:
    - tox
